import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ 
  subsets: ["latin"], 
  variable: '--font-inter' 
});

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ['500', '600'],
  variable: '--font-poppins'
});

export const metadata = {
  title: "FormAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" >
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      {/* CORRECT: We use the .variable property from our consts above */}
      <body className={`${inter.variable} ${poppins.variable} font-sans`}>
        <Header/>
        {children}
        <Toaster />
      </body>
    </html>
    </ClerkProvider>
  );
}